#!/usr/bin/env node
// Only Refresh — build src/i18n.js from tools/i18n/*.json (deterministic).
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Only Refresh contributors.
//
// Usage:  node tools/build_i18n.js
// Reads the per-language JSON files, validates every locale has the English
// key set, and emits the bundled src/i18n.js consumed by the popup and picker.

const fs = require('fs');
const path = require('path');

const ORDER = ['en', 'de', 'fr', 'es', 'zh', 'ja', 'ko', 'ru'];
const i18nDir = path.join(__dirname, 'i18n');
const outFile = path.join(__dirname, '..', 'src', 'i18n.js');

const en = JSON.parse(fs.readFileSync(path.join(i18nDir, 'en.json'), 'utf8'));
const keys = Object.keys(en);

const messages = {};
let ok = true;
for (const code of ORDER) {
  const f = path.join(i18nDir, code + '.json');
  if (!fs.existsSync(f)) { console.error('MISSING locale file:', code + '.json'); ok = false; continue; }
  const obj = JSON.parse(fs.readFileSync(f, 'utf8'));
  const missing = keys.filter((k) => !(k in obj));
  const extra = Object.keys(obj).filter((k) => keys.indexOf(k) === -1);
  if (missing.length) { console.error(code, 'missing keys:', missing.join(', ')); ok = false; }
  if (extra.length) console.warn(code, 'extra keys (ignored):', extra.join(', '));
  const clean = {};                       // keep only known keys, in English order
  for (const k of keys) clean[k] = (k in obj) ? obj[k] : en[k];
  messages[code] = clean;
}
if (!ok) { console.error('Build aborted: locales incomplete.'); process.exit(1); }

const MESSAGES_JSON = JSON.stringify(messages, null, 2);

const out = `// Only Refresh — i18n bundle (GENERATED by tools/build_i18n.js — do not edit by hand).
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Only Refresh contributors.
//
// Regenerate after editing tools/i18n/*.json:  node tools/build_i18n.js

(function () {
  'use strict';

  const MESSAGES = ${MESSAGES_JSON};

  // Language picker entries: '' follows the browser; the rest are endonyms.
  const LANGS = [
    { code: '', name: 'Auto' },
    { code: 'en', name: 'English' },
    { code: 'de', name: 'Deutsch' },
    { code: 'fr', name: 'Français' },
    { code: 'es', name: 'Español' },
    { code: 'zh', name: '中文' },
    { code: 'ja', name: '日本語' },
    { code: 'ko', name: '한국어' },
    { code: 'ru', name: 'Русский' }
  ];
  const SUPPORTED = ['en', 'de', 'fr', 'es', 'zh', 'ja', 'ko', 'ru'];

  // The browser's language, mapped to a supported code (fallback 'en').
  function detect() {
    let l = 'en';
    try { l = navigator.language || 'en'; } catch (e) { l = 'en'; }
    const primary = String(l).toLowerCase().split('-')[0];
    return SUPPORTED.indexOf(primary) !== -1 ? primary : 'en';
  }

  // Effective language: an explicit, supported choice wins; otherwise the browser.
  function resolve(chosen) {
    return (chosen && SUPPORTED.indexOf(chosen) !== -1) ? chosen : detect();
  }

  // Translate \`key\` for \`lang\`, substituting {placeholders} from \`params\`.
  // Falls back to English, then to the raw key.
  function t(lang, key, params) {
    const table = MESSAGES[lang] || MESSAGES.en;
    let s = (table && table[key] != null) ? table[key]
          : (MESSAGES.en[key] != null ? MESSAGES.en[key] : key);
    if (params) {
      for (const p in params) s = s.split('{' + p + '}').join(String(params[p]));
    }
    return s;
  }

  self.OnlyRefreshI18n = { MESSAGES, LANGS, SUPPORTED, detect, resolve, t };
})();
`;

fs.writeFileSync(outFile, out, 'utf8');
console.log('Wrote', path.relative(process.cwd(), outFile), '—', ORDER.length, 'locales,', keys.length, 'keys');
